import { _decorator, Component, Node } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('OPNameCharacter')
export class OPNameCharacter {
    static listAllName : any[] = [
        {id:0, nameChar:"Jolly Straw Hat"},
        {id:1, nameChar:"Abdullah"},
        {id:2, nameChar:"Acilia"},
        {id:3, nameChar:"Adele"},
        {id:4, nameChar:"Agyo"},
        {id:5, nameChar:"Akehende"},
        {id:6, nameChar:"albion"},
        {id:7, nameChar:"Alpacaman"},
        {id:8, nameChar:"Alvida"},
        {id:10, nameChar:"AO"},
        {id:11, nameChar:"Arlong"},
        {id:12, nameChar:"Atmos"},
        {id:13, nameChar:"Azuki"},
        {id:14, nameChar:"Babe"},
        {id:15, nameChar:"Baby 5"},
        {id:16, nameChar:"Bakkin"},
        {id:17, nameChar:"Ban Dedessinee"},
        {id:18, nameChar:"Banchi"},
        {id:19, nameChar:"Bariette"},
        {id:20, nameChar:"Baskerville"},
        {id:21, nameChar:"Bastile"},
        {id:22, nameChar:"Batman"},
        {id:23, nameChar:"Bellamy"},
        {id:24, nameChar:"Benn Beckman"},
        {id:25, nameChar:"Berr VI"},
        {id:26, nameChar:"Big Pan"},
        {id:27, nameChar:"Blackback"},
        {id:28, nameChar:"Blenheim"},
        {id:29, nameChar:"Buffalo"},
        {id:30, nameChar:"Buhincuck"},
        {id:31, nameChar:"Cabaji"},
        {id:32, nameChar:"Capote"},
        {id:33, nameChar:"Carberus"},
        {id:34, nameChar:"Caribou"},
        {id:35, nameChar:"Charlos"},
        {id:36, nameChar:"Charlotte chiboust"},
        {id:37, nameChar:"Charlotte High-Fat"},
        {id:38, nameChar:"Charlotte Lola"},
        {id:39, nameChar:"Charlotte Praline"},
        {id:40, nameChar:"Chess"},
        {id:41, nameChar:"Chew"},
        {id:42, nameChar:"Choco"},
        {id:43, nameChar:"ChouChou"},
        {id:44, nameChar:"Clione"},
        {id:45, nameChar:"Comil"},
        {id:46, nameChar:"Conis"},
        {id:47, nameChar:"Coribou"},
        {id:48, nameChar:"Cotton"},
        {id:49, nameChar:"Dellinger"},
        {id:50, nameChar:"Denjiro"},
        {id:51, nameChar:"Devil Dias"},
        {id:52, nameChar:"Diamante"},
        {id:53, nameChar:"Didit (Sabo Mother)"},
        {id:54, nameChar:"Doberman"},
        {id:55, nameChar:"Donquixote Doflamingo"},
        {id:56, nameChar:"Dorry"},
        {id:57, nameChar:"Edward Weevil"},
        {id:58, nameChar:"Faust (mink)"},
        {id:59, nameChar:"Fukuro"},
        {id:60, nameChar:"Galdino (Mr 3)"},
        {id:61, nameChar:"Gatz"},
        {id:62, nameChar:"Gazelleman"},
        {id:63, nameChar:"Giolla"},
        {id:64, nameChar:"Gion"},
        {id:65, nameChar:"Giro Chintaro"},
        {id:66, nameChar:"Glove"},
        {id:67, nameChar:"Hamburg"},
        {id:68, nameChar:"Hanzo"},
        {id:69, nameChar:"Haredas"},
        {id:70, nameChar:"hihimaru"},
        {id:71, nameChar:"Hildon"},
        {id:72, nameChar:"Hody Jones"},
        {id:73, nameChar:"Ideo"},
        {id:74, nameChar:"Inazuma"},
        {id:75, nameChar:"Indigo"},
        {id:76, nameChar:"Inhel"},
        {id:77, nameChar:"Izou"},
        {id:78, nameChar:"Jaguar D. saul"},
        {id:79, nameChar:"Jorul"},
        {id:80, nameChar:"Kabu"},
        {id:81, nameChar:"Kaku"},
        {id:82, nameChar:"Kalifa"},
        {id:83, nameChar:"Kashii"},
        {id:84, nameChar:"Kibin"},
        {id:85, nameChar:"Killer"},
        {id:86, nameChar:"Kinderella"},
        {id:87, nameChar:"Kingbaum"},
        {id:88, nameChar:"Kkunojo"},
        {id:89, nameChar:"Kuina"},
        {id:90, nameChar:"Kumadori"},
        {id:91, nameChar:"kumashi"},
        {id:92, nameChar:"Kurozomi Kanjuro"},
        {id:93, nameChar:"Kurozumi Higurashi"},
        {id:94, nameChar:"Laboon"},
        {id:95, nameChar:"Leo"},
        {id:96, nameChar:"Lola (Zombie)"},
        {id:97, nameChar:"Marianne (partner Mr.3)"},
        {id:98, nameChar:"Marshall D. Teach (Balckbird)"},
        {id:99, nameChar:"Masira"},
        {id:100, nameChar:"Maynard"},
        {id:101, nameChar:"Megalo"},
        {id:102, nameChar:"Miss Friday"},
        {id:103, nameChar:"Momonga"},
        {id:104, nameChar:"Moublutain (Fake Straw Hat Usopp)"},
        {id:105, nameChar:"Mozu and Kiwi"},
        {id:106, nameChar:"Nekomamushi"},
        {id:107, nameChar:"Neptune"},
        {id:108, nameChar:"Nezumi"},
        {id:109, nameChar:"Nubon"},
        {id:110, nameChar:"Oars"},
        {id:111, nameChar:"Octapako"},
        {id:112, nameChar:"Ohm"},
        {id:113, nameChar:"Onigumo"},
        {id:114, nameChar:"Orlumbus"},
        {id:115, nameChar:"Pekoms"},
        {id:116, nameChar:"Pell"},
        {id:117, nameChar:"Penguin"},
        {id:118, nameChar:"Poker"},
        {id:119, nameChar:"Portgas D. Rouge (Ace Mother)"},
        {id:120, nameChar:"Rabiyan"},
        {id:121, nameChar:"Randolph"},
        {id:122, nameChar:"Rika"},
        {id:123, nameChar:"Sakazuki"},
        {id:124, nameChar:"Sarahebi"},
        {id:125, nameChar:"Ukon"},
        {id:126, nameChar:"Vinsmoke Yonji"},
        {id:127, nameChar:"Zotto"}, /// btn 1
        {id:128, nameChar:"Absalom"},
        {id:129, nameChar:"Agotogi"},
        {id:130, nameChar:"Akuda"},
        {id:131, nameChar:"Akudai Kanzaburo"},
        {id:132, nameChar:"Akumai"},
        {id:133, nameChar:"Avalo Pizarro"},
        {id:134, nameChar:"Babanuki"},
        {id:135, nameChar:"Bankuro"},
        {id:136, nameChar:"Bao Huang"},
        {id:137, nameChar:"barry"},
        {id:138, nameChar:"Basil Hawkins"},
        {id:139, nameChar:"Belo Betty"},
        {id:140, nameChar:"Black maria"},
        {id:141, nameChar:"Blamenco"},
        {id:142, nameChar:"Blue Gilly"},
        {id:143, nameChar:"Blue Jam"},
        {id:144, nameChar:"Boa Marigold"},
        {id:145, nameChar:"Boa Sandersonia"},
        {id:146, nameChar:"Brannew"},
        {id:147, nameChar:"Brogy"},
        {id:148, nameChar:"Caimanlady"},
        {id:149, nameChar:"Capone Bege"},
        {id:150, nameChar:"capone Pez"},
        {id:151, nameChar:"Carmel"},
        {id:152, nameChar:"Charlotte Amande"},
        {id:153, nameChar:"Charlotte Basskarte"},
        {id:154, nameChar:"Charlotte Brownie"},
        {id:155, nameChar:"Charlotte Chiffon"},
        {id:156, nameChar:"Charlotte Cinnamon"},
        {id:157, nameChar:"Charlotte Compote"},
        {id:158, nameChar:"Charlotte Cracker"},
        {id:159, nameChar:"Charlotte Effile"},
        {id:160, nameChar:"Concelot"},
        {id:161, nameChar:"Crocodile"},
        {id:162, nameChar:"Crocus"},
        {id:163, nameChar:"Curly Dadan"},
        {id:164, nameChar:"Dagama"},
        {id:165, nameChar:"Daigin"},
        {id:166, nameChar:"Daikoku"},
        {id:167, nameChar:"Dalmation"},
        {id:168, nameChar:"Dalton"},
        {id:169, nameChar:"Donquixote Rosinante"},
        {id:170, nameChar:"Dracule Mihawk"},
        {id:171, nameChar:"Eggplant Soldier"},
        {id:172, nameChar:"Elizabello II"},
        {id:173, nameChar:"Fillonce"},
        {id:174, nameChar:"Foxy"},
        {id:175, nameChar:"Fujin"},
        {id:176, nameChar:"Gan fall"},
        {id:177, nameChar:"Gedatsu"},
        {id:178, nameChar:"Ginrummy"},
        {id:179, nameChar:"Gladius"},
        {id:180, nameChar:"Guernica"},
        {id:181, nameChar:"Hajrudin"},
        {id:182, nameChar:"Helmeppo"},
        {id:183, nameChar:"Heracles"},
        {id:184, nameChar:"Hiriluk"},
        {id:185, nameChar:"Hogback"},
        {id:186, nameChar:"Igaram"},
        {id:187, nameChar:"Inuppe"},
        {id:188, nameChar:"Jack"},
        {id:189, nameChar:"Jesus Burgess"},
        {id:190, nameChar:"Kaidou"},
        {id:191, nameChar:"Kalgara"},
        {id:192, nameChar:"Karasu"},
        {id:193, nameChar:"Kin'emon"},
        {id:194, nameChar:"Kokoro"},
        {id:195, nameChar:"Kozuki Hiyori"},
        {id:196, nameChar:"Kozuki Oden"},
        {id:197, nameChar:"Kureha"},
        {id:198, nameChar:"Kuzan (Aokji)"},
        {id:199, nameChar:"Magellan"},
        {id:200, nameChar:"Milky"},
        {id:201, nameChar:"Monet"},
        {id:202, nameChar:"Morgan"},
        {id:203, nameChar:"Morley"},
        {id:204, nameChar:"Nico Olvia)"},
        {id:205, nameChar:"Nitro"},
        {id:206, nameChar:"Nola"},
        {id:207, nameChar:"Outlook III (sabo father)"},
        {id:208, nameChar:"Pagaya"},
        {id:209, nameChar:"Pappag"},
        {id:210, nameChar:"Paulie"},
        {id:211, nameChar:"Pica"},
        {id:212, nameChar:"Queen"},
        {id:213, nameChar:"Raizo"},
        {id:214, nameChar:"Rampo"},
        {id:215, nameChar:"Riku Doldo III"},
        {id:216, nameChar:"Ripper"},
        {id:217, nameChar:"Rob Lucci"},
        {id:218, nameChar:"Roshio"},
        {id:219, nameChar:"Russian"},
        {id:220, nameChar:"Sadi"},
        {id:221, nameChar:"Satori"},
        {id:222, nameChar:"Scarlett"},
        {id:223, nameChar:"Senor Pink"},
        {id:224, nameChar:"Sentomaru"},
        {id:225, nameChar:"Shachi"},
        {id:226, nameChar:"Shakuyaku"},
        {id:227, nameChar:"Shimotsuki Ryuma"},
        {id:228, nameChar:"Shinosuke"},
        {id:229, nameChar:"Shiryu"},
        {id:230, nameChar:"Shishilian"},
        {id:231, nameChar:"Sind"},
        {id:232, nameChar:"Speed"},
        {id:233, nameChar:"Stainless"},
        {id:234, nameChar:"Stussy"},
        {id:235, nameChar:"Sugar"},
        {id:236, nameChar:"Surume"},
        {id:237, nameChar:"T Bone"},
        {id:238, nameChar:"Takao"},
        {id:239, nameChar:"Tibany"},
        {id:240, nameChar:"Tilestone"},
        {id:241, nameChar:"Tom"},
        {id:242, nameChar:"Trebol"},
        {id:243, nameChar:"Tsugaru umi"},
        {id:244, nameChar:"Ulti"},
        {id:245, nameChar:"Urouge"},
        {id:246, nameChar:"Vergo"},
        {id:247, nameChar:"Victoria Cindry"},
        {id:248, nameChar:"Vinsmoke Ichiji"},
        {id:249, nameChar:"Wanze"},
        {id:250, nameChar:"Wapol"},
        {id:251, nameChar:"Yamakaji"},
        {id:252, nameChar:"Yorki"}, /// btn 2
        {id:253, nameChar:"aladine"},
        {id:254, nameChar:"Ashura Doji"},
        {id:255, nameChar:"Bartholomew Kuma"},
        {id:256, nameChar:"Bartolomeo"},
        {id:257, nameChar:"BellMere"},
        {id:258, nameChar:"Bepo"},
        {id:259, nameChar:"Bian"},
        {id:260, nameChar:"Bishamon"},
        {id:261, nameChar:"Blueno"},
        {id:262, nameChar:"Boa Hancock"},
        {id:263, nameChar:"Bobby Funk"},
        {id:264, nameChar:"bon kurei(Mr.2)"},
        {id:265, nameChar:"borsalino"},
        {id:266, nameChar:"brook"},
        {id:267, nameChar:"Buggy"},
        {id:268, nameChar:"caesar clown"},
        {id:269, nameChar:"camie"},
        {id:270, nameChar:"Carrot"},
        {id:271, nameChar:"Catarina Devon"},
        {id:272, nameChar:"Cavendish"},
        {id:273, nameChar:"Chadros Higelyges"},
        {id:274, nameChar:"Chao"},
        {id:275, nameChar:"Charlotte Brulle"},
        {id:276, nameChar:"Charlotte Dolce and Dragee"},
        {id:277, nameChar:"Charlotte Flampe"},
        {id:278, nameChar:"Charlotte Galette"},
        {id:279, nameChar:"Charlotte Katakuri"},
        {id:280, nameChar:"Charlotte Linlin "},
        {id:281, nameChar:"Charlotte Pudding"},
        {id:282, nameChar:"Cho"},
        {id:283, nameChar:"Cosette"},
        {id:284, nameChar:"Damaro Black (Fake Straw Hat Luffy)"},
        {id:285, nameChar:"Duval"},
        {id:286, nameChar:"Edward Newgate (Whitebeard)"},
        {id:287, nameChar:"Emporio Ivankov"},
        {id:288, nameChar:"Enel"},
        {id:289, nameChar:"Eustass Kid"},
        {id:290, nameChar:"Fisher Tiger"},
        {id:291, nameChar:"Flapper"},
        {id:292, nameChar:"Franky"},
        {id:293, nameChar:"Fukaboshi"},
        {id:294, nameChar:"Gaimon"},
        {id:295, nameChar:"Gecko Moria"},
        {id:296, nameChar:"Gem (Mr.5)"},
        {id:297, nameChar:"Gimlet"},
        {id:298, nameChar:"Gin"},
        {id:299, nameChar:"Ginnosuke"},
        {id:300, nameChar:"Giovanni"},
        {id:301, nameChar:"Gloriosa"},
        {id:302, nameChar:"Gol D. Roger"},
        {id:303, nameChar:"Hasami"},
        {id:304, nameChar:"Hatchan"},
        {id:305, nameChar:"Hina"},
        {id:306, nameChar:"Hoe"},
        {id:307, nameChar:"Holy"},
        {id:308, nameChar:"iceburg"},
        {id:309, nameChar:"Inuarashi"},
        {id:310, nameChar:"Issho"},
        {id:311, nameChar:"Jewelry Bonney"},
        {id:312, nameChar:"Jigoku Benten"},
        {id:313, nameChar:"Jinbe"},
        {id:314, nameChar:"Karoo"},
        {id:315, nameChar:"Kaya"},
        {id:316, nameChar:"Koala"},
        {id:317, nameChar:"Koby"},
        {id:318, nameChar:"Kozuku Momonosuke"},
        {id:319, nameChar:"Krieg"},
        {id:320, nameChar:"Kyros"},
        {id:321, nameChar:"Makino"},
        {id:322, nameChar:"Manjaro (Fake Straw Hat Zoro)"},
        {id:323, nameChar:"Mansherry"},
        {id:324, nameChar:"Marco"},
        {id:325, nameChar:"Monkey D. Dragon"},
        {id:326, nameChar:"Monkey D. Garp"},
        {id:327, nameChar:"Monkey D. luffy"},
        {id:328, nameChar:"Nami"},
        {id:329, nameChar:"Nefertari vivi"},
        {id:330, nameChar:"Nico Robin"},
        {id:331, nameChar:"Nora Gitsune (Fake Straw hat Chopper)"},
        {id:332, nameChar:"Otohime"},
        {id:333, nameChar:"Pedro"},
        {id:334, nameChar:"Perona"},
        {id:335, nameChar:"Portgas D. Ace"},
        {id:336, nameChar:"Pound"},
        {id:337, nameChar:"Rebecca"},
        {id:338, nameChar:"Roronoa Zoro"},
        {id:339, nameChar:"Rosward"},
        {id:340, nameChar:"Ryunosuke"},
        {id:341, nameChar:"Sabo"},
        {id:342, nameChar:"Sanji"},
        {id:343, nameChar:"Sengokku"},
        {id:344, nameChar:"Shandia Chief"},
        {id:345, nameChar:"Shanks"},
        {id:346, nameChar:"Sheepshead"},
        {id:347, nameChar:"Shiki"},
        {id:348, nameChar:"Shirahoshi"},
        {id:349, nameChar:"Shyarly"},
        {id:350, nameChar:"Silvers Rayleigh"},
        {id:351, nameChar:"Smoker"},
        {id:352, nameChar:"Spartan"},
        {id:353, nameChar:"Sterry"},
        {id:354, nameChar:"Tama"},
        {id:355, nameChar:"Tamago"},
        {id:356, nameChar:"Tashigi"},
        {id:357, nameChar:"Tenjo-Sagari"},
        {id:358, nameChar:"Toko"},
        {id:359, nameChar:"Tony Tony Chopper"},
        {id:360, nameChar:"Trafalgar D. Water Law"},
        {id:361, nameChar:"Tristan"},
        {id:362, nameChar:"Tsuru"},
        {id:363, nameChar:"Usopp"},
        {id:364, nameChar:"Uta"},
        {id:365, nameChar:"Vinsmoke Judge"},
        {id:366, nameChar:"Vinsmoke Niji"},
        {id:367, nameChar:"Vinsmoke Reiju"},
        {id:368, nameChar:"Vinsmoke Sora"},
        {id:369, nameChar:"Viola"},
        {id:370, nameChar:"Wadatsumi"},
        {id:371, nameChar:"Wanda"},
        {id:372, nameChar:"Yamato"},
        {id:373, nameChar:"Yasopp"},
        {id:374, nameChar:"Zeff"},
        {id:375, nameChar:"Zepo"},
        {id:376, nameChar:"Zeus"},
        {id:377, nameChar:"Zunesha"}
    ];
}


